name: Trigger on secrets.yaml change

on:
  push:
    paths:
      - 'secrets.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get TELE_TOKEN from Secret Manager
      id: secret
      uses: GoogleCloudPlatform/github-actions/get-secretmanager-secret@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        secret_id: ${{ secrets.GCP_SECRET_ID }}
        version: latest

    - name: Edit secrets.yaml
      uses: mikefarah/yq@master
      with:
        cmd: echo ${{ steps.secret.outputs.secret_data.TELE_TOKEN }} && yq -i '.image.tag=${{ steps.secret.outputs.secret_data.TELE_TOKEN }}' helm/values.yaml
        
    - name: Encrypt Secrets
      run: |
        sops --encrypt --in-place secrets.yaml
        mv secrets.yaml secrets-enc.yaml

    - name: Commit and Push Encrypted Secrets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add secrets-enc.yaml
        git commit -m "Encrypt and commit secrets"
        git push