name: Trigger on secrets.yaml change

on:
  push:
    paths:
      - 'secrets.yaml'

jobs:
  encoding:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_GITHUB_ACTIONS_KEY }}
    
    - name: Sops Binary Installer
      id: 'install'
      uses: mdgreenwald/mozilla-sops-action@v1.4.1

    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
          token:${{ secrets.GCP_PROJECT_ID }}/TELE_TOKEN

    - name: Edit secrets.yaml
      uses: mikefarah/yq@master
      with:
        cmd: |
          echo ${{ steps.secrets.outputs.token }}
          yq -i '.data.token="${{ steps.secrets.outputs.token }}"' secrets.yaml
        
    - name: Encrypt Secrets
      run: |
        sops --encrypt --gcp-kms ${{ secrets.KEYRING_SOURCE }} secrets.yaml > secrets-enc.yaml

    - name: Commit and Push Encrypted Secrets
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add secrets-enc.yaml
        git commit -m "Encrypt and commit secrets"
        git push
